### ISSUE TITLE
What should happen after a QR code is scanned? 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Superformula/mobile-test#24]
What's an example demonstration of how the scan works?
Like the expected flow.

**Comment by brianb-sf** [comment]
Hey @ThinkDigitalSoftware! Thanks for the question.

The expected flow is something like
Camera opens -> Scan QR Code -> Loading state if needed -> Screen or dialog that says if the code is valid or not.

Let us know if you have anymore questions!
