### ISSUE TITLE
QR Code validity rule

### ISSUE THREAD

**Issue by edgarfroes** [Superformula/mobile-test#31]
Is the expiration the only parameter that defines if a QR Code is valid or not?

For instance: if user A is displaying an expired QR Code (given that the automatic QR Code update functionality is not implemented) and user B reads the QR Code, user B would get an "invalid QR Code" message. Can this be the correct flow?

**Comment by brianb-sf** [comment]
@edgarfroes Yes that is correct. A QR code is valid if and only if it has not expired. The scenario you described is the expected behavior. Thanks for the question and let us know if you have any more!
