### ISSUE TITLE
Lambda API

### ISSUE THREAD

**Issue by edgarfroes** [Superformula/mobile-test#32]
In your docs, you said you can provide me with a Lambda API.

Can you please do it for me?

**Comment by brianb-sf** [comment]
Hi @edgarfroes,

We have sent you an email with the Lamdba information that you can use.

Thanks!

**Comment by edgarfroes** [comment]
@brianb-sf It looks like I haven't received your email. Could you please check that out?

**Comment by brianb-sf** [comment]
@edgarfroes sorry about that 😄 , please check your email again.
