### ISSUE TITLE
Home UI 

### ISSUE THREAD

**Issue by jafri-zz** [Superformula/mobile-test#34]
A couple of questions: 

1. Is the Home UI expected to match the mockup exactly? Or is that provided merely as a loose guide? 
2. If so, are the "QRCode" and "Scan" options intended to be radio buttons that indicate which selection should get activated when the FAB is tapped?

**Comment by brianb-sf** [comment]
@jafri-zz Thanks for the question! 

The mockup is a loose guide but the intent is that it uses the speed dial like floating action button that when tapped reveals the `Scan` and `QR Code` option. This gif better illustrates what was intended by the mock up.

![1_El9w3fPX45eIu-7CH4VN-Q](https://user-images.githubusercontent.com/51182634/106531374-539e4a80-64ab-11eb-9c3e-92940520a166.gif)

Let us know if you have any more questions!
