### ISSUE TITLE
I'm not able to build an API server

### ISSUE THREAD

**Issue by MatheusMassula** [Superformula/mobile-test#44]
Good morning!

I'm doing the QR Code Challenge, but I don't know how to create the backend.

Can you provide me the endpoint needed to make the QR code challenge?

Regards,
Matheus Massula

**Comment by MatheusMassula** [comment]
I've another question...
What should happen after the timer expires?
Should I call the API again?  Getting a new QR Code

**Comment by jeffs-sf** [comment]
Good morning Matheus!

---

With regards to:

> Can you provide me the endpoint needed to make the QR code challenge?

I just sent an email with the necessary information regarding this. Please keep an eye out for it.

---

With regards to:

> What should happen after the timer expires?
> Should I call the API again? Getting a new QR Code

That is ultimately up to you and what you determine the best user experience would be in that situation. Please note that there is an item under the Advanced requirements (think bonus) that states:
> Provide an auto-refresh strategy, for example with the expires_at value.

---

Let us know if you have any other questions!
