### ISSUE TITLE
Lambda/API Request

### ISSUE THREAD

**Issue by leandromichelforte** [Superformula/mobile-test#74]
Hello guys,

Hope this message finds you well.

I'm doing this assessment for a Flutter Engineer position and I'm requesting the lambda/API to finish.

Regards.

**Comment by diegog-sf** [comment]
Hey, you can include a [small local node.js server with it](https://medium.com/@dhwajgupta27/build-a-node-js-server-in-5-minutes-quick-and-easy-server-setup-6eb594e8b26) (or any language that you prefer), if you're having troubles, you can mock the response

**Comment by leandromichelforte** [comment]
I got it!

Thank you.

I'll send my pull request asap.
