### ISSUE TITLE
Not sure what the "+" button is for

### ISSUE THREAD

**Issue by mmaitlen** [Superformula/mobile-test#9]
If I understand the mockup correctly, the Scan button takes you to the scan screen, QRCode button takes you to the QRCode screen but I'm not sure what the "+" button is and what it's used for.  A guess from the mock up is that when the app opens the "+" is visible, when pressed the Scan and QRCode buttons are displayed.

**Comment by wprater** [comment]
When you hit the `+`, it would reveal the other action buttons until tapped again or the other action buttons are hit.  

See here https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

cc @scottbaggett
